### PR TITLE
update videos

### PR DESCRIPTION
**Pull request by ungoldman**
updated the video section with latest presentations:

screen shot 2017-10-11 at 2 00 28 pm

### CODE REVIEW

**Comment by ungoldman** [comment]
@PDXNode/core plz 2 approve

**Review by bcomnes — APPROVED** [review]

**Comment by obensource** [comment]
@ungoldman can we do Paul and Suz Hinton's talks? Just want to have some diversity represented there. :)

**Comment by obensource** [comment]
Thanks for keeping us updated @ungoldman!

**Comment by obensource** [comment]
Ah but it's 'latest' I see. Sorry, not feeling well today. Your call, I'll approve either way. :)

**Review by obensource — APPROVED** [review]

**Pull request merged**
